name: CI / CD with Azure App Service

on:
  workflow_dispatch:    

env:
  AZURE_WEBAPP_NAME: DEVOPSTST  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 -> Checkout main branch from Github
      uses: actions/checkout@v2
    - name: Step 2 -> Set Up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Step 3 -> Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2        
    - name: Step 4 -> Build Maven Project
      run: |
        mvn -B clean package -DskipTests --file pom.xml
        mkdir staging && cp target/*.jar staging
    - name: Step 5 -> List the current directory
      run: ls -a
    - name: Step 6 -> Deploy tp Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: target/*.jar